language: python

python:
  - 3.5
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial     # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required   # required for Python 3.7 (travis-ci/travis-ci#9069)

install:
  - pip install -r requirements_dev.txt

before_script:
  cd tests/

script:
  - flake8
  - coverage run --source=../source -m pytest

after_success:
  - coveralls
